export const allBlogs = [
    {
        id: 1,
        title: '10 Tips for Efficient CSS Coding',
        category: 'development',
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'TechDevPro',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '15.06.2023',
        cover: '/assets/images/1.jpg',
    },
    {
        id: 2,
        title: 'CSS Best Practices for Responsive Web Design',
        category: 'development',
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'WebDevGuru',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '15.06.2023',
        cover: '/assets/images/2.jpg',
    },
    {
        id: 3,
        title: 'Introduction to Machine Learning',
        category: 'technology',
        subCategory: ['artificial intelligence', 'data science'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'AI Enthusiast',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '13.06.2023',
        cover: '/assets/images/3.jpg',
    },
    {
        id: 4,
        title: 'Healthy Recipes for a Balanced Diet',
        category: 'health',
        subCategory: ['nutrition', 'cooking'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'HealthyChef',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '12.06.2023',
        cover: '/assets/images/4.jpg',
    },
    {
        id: 5,
        title: 'Financial Planning: Tips for a Secure Future',
        category: 'finance',
        subCategory: ['investing', 'budgeting'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Financial Guru',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '12.06.2023',
        cover: '/assets/images/5.jpg',
    },
    {
        id: 6,
        title: 'Effective Time Management Techniques',
        category: 'self-improvement',
        subCategory: ['productivity', 'lifestyle'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Personal Development Coach',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '11.06.2023',
        cover: '/assets/images/6.jpg',
    },
    {
        id: 7,
        title: 'Exploring the World of Art: A Beginner\'s Guide',
        category: 'art',
        subCategory: ['painting', 'sculpture', 'installation'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Art Enthusiast',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '11.06.2023',
        cover: '/assets/images/7.jpg',
    },
    {
        id: 8,
        title: 'Effective Communication in the Workplace',
        category: 'business',
        subCategory: ['leadership', 'teamwork'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Business Consultant',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '10.06.2023',
        cover: '/assets/images/8.jpg',
    },
    {
        id: 9,
        title: 'Gardening Tips for Beautiful and Healthy Plants',
        category: 'home & garden',
        subCategory: ['landscaping', 'plant care'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Green Thumb',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '09.06.2023',
        cover: '/assets/images/9.jpg',
    },
    {
        id: 10,
        title: 'Exploring the World of Photography',
        category: 'art',
        subCategory: ['photography', 'editing'],
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at diam quis mi fringilla luctus at non lectus. Phasellus non tellus semper, faucibus metus a, auctor ipsum. Morbi ullamcorper risus eget enim accumsan, id pulvinar dui suscipit.',
        authorName: 'Photography Enthusiast',
        authorAvatar: '/assets/images/avatar.png',
        createdAt: '08.06.2023',
        cover: '/assets/images/10.jpg',
    }
]